"""Add improved database models

Revision ID: 5d2faa752530
Revises: 9ad5971a7cc7
Create Date: 2025-11-22 22:51:49.402526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2faa752530'
down_revision: Union[str, None] = '9ad5971a7cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_items', 'location_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'location_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'sale_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'sale_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'location_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory_items', 'location_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
